Revert "Make byte spans check for unique obj representations."
This reverts commit 6408cb7badf528f7c71620e5b40a80155bfa5d50.

Reason for revert: Suspected for build failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/chromeos-arm-generic-dbg/105802/blamelist
Step compile failed. Error logs are shown below:
[8013/49103] CXX obj/media/gpu/v4l2/v4l2/v4l2_mjpeg_decode_accelerator.o
../../build/cros_cache/chrome-sdk/symlinks/arm-generic+16124.0.0-1065359+target_toolchain/bin/armv7a-cros-linux-gnueabihf-clang++ -MMD -MF obj...(too long)
../../media/gpu/v4l2/v4l2_mjpeg_decode_accelerator.cc:602:9: error: no matching function for call to 'byte_span_from_ref'
  602 |         base::byte_span_from_ref(base::allow_nonunique_obj, buffer), 0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
../../base/containers/span.h:1562:16: note: candidate template ignored: constraints not satisfied [with T = struct v4l2_buffer]
 1562 | constexpr auto byte_span_from_ref(allow_nonunique_obj_t,
      |                ^

Original change's description:
> Make byte spans check for unique obj representations.
>
> Bug: 382041497
> Low-Coverage-Reason: LARGE_SCALE_REFACTOR no meaningful change in the relevant files
> Change-Id: Iea2e0397b770af3bfd95c05a9983f315c5bc47a7
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6081833
> Owners-Override: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Commit-Queue: Peter Kasting <pkasting@chromium.org>
> Auto-Submit: Peter Kasting <pkasting@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1396262}

Bug: 382041497
Change-Id: I719601fbe366d5f7f1ed2621ae4f4de1c07e57c4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6094647
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Mike Wasserman <msw@google.com>
Commit-Queue: Mike Wasserman <msw@chromium.org>
Auto-Submit: Mike Wasserman <msw@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1396276}
NOKEYCHECK=True
GitOrigin-RevId: 7007d46b8e7b222df0b5ff4e3e8ade7ffc61b6f6